import type {
  Client,
  ClientDetail,
  ClientDocument,
  ClientNote,
  ClientSurvey,
} from "./types";

export const DEMO_CLIENTS: Client[] = [
  {
    id: "CL-1001",
    name: "Иван Петров",
    phone: "+34 612 345 678",
    email: "ivan.petrov@email.com",
    country: "Россия",
    citizenship: "РФ",
    direction: "Испания",
    status: "В работе",
    manager: "Менеджер 1",
    lastActivity: "28.05.2026",
    createdAt: "12.03.2026",
  },
  {
    id: "CL-1002",
    name: "Анна Коваль",
    phone: "+385 91 234 5678",
    email: "anna.k@email.com",
    country: "Хорватия",
    citizenship: "Украина",
    direction: "Хорватия",
    status: "Консультация",
    manager: "Инспектор Marko Horvat",
    lastActivity: "27.05.2026",
    createdAt: "05.04.2026",
    passportNumber: "UA1234567",
    submittedAt: "05.04.2026",
    expectedApprovalAt: "15.07.2026",
    referentName: "Инспектор Marko Horvat",
    bookingAddress: "Zagreb, Ilica 42",
    bookingRange: "20.05.2026 — 25.05.2026",
    approvalAt: "—",
    notes: "Лист ожидания, документы отправлены",
    residenceCardIssuedAt: "—",
  },
  {
    id: "CL-1003",
    name: "Marcus Weber",
    phone: "+421 905 123 456",
    email: "marcus.weber@email.com",
    country: "Германия",
    citizenship: "Германия",
    direction: "Словакия",
    status: "Новый",
    manager: "Вероника",
    lastActivity: "26.05.2026",
    createdAt: "20.05.2026",
  },
  {
    id: "CL-1004",
    name: "Sofia Mendes",
    phone: "+351 912 345 678",
    email: "sofia.m@email.com",
    country: "Бразилия",
    citizenship: "Бразилия",
    direction: "Португалия",
    status: "Подготовка документов",
    manager: "Менеджер 3",
    lastActivity: "25.05.2026",
    createdAt: "18.01.2026",
  },
  {
    id: "CL-1005",
    name: "Елена Смирнова",
    phone: "+7 916 555 0123",
    email: "elena.s@email.com",
    country: "Россия",
    citizenship: "РФ",
    direction: "Испания",
    status: "Завершён",
    manager: "Менеджер 1",
    lastActivity: "20.05.2026",
    createdAt: "10.11.2025",
  },
  {
    id: "CL-1006",
    name: "Tomáš Novák",
    phone: "+420 777 888 999",
    email: "tomas.n@email.com",
    country: "Хорватия",
    citizenship: "Чехия",
    direction: "Хорватия",
    status: "В работе",
    manager: "Инспектор Ana Marić",
    lastActivity: "24.05.2026",
    createdAt: "02.02.2026",
    passportNumber: "CZ9988776",
    submittedAt: "02.02.2026",
    expectedApprovalAt: "01.06.2026",
    referentName: "Инспектор Ana Marić",
    bookingAddress: "Split, Marmontova 12",
    bookingRange: "15.04.2026 — 18.04.2026",
    approvalAt: "—",
    notes: "Дозапрос документов по доходу",
    residenceCardIssuedAt: "—",
  },
  {
    id: "CL-2001",
    name: "Maria Rossi",
    phone: "+39 333 111 2222",
    email: "maria.r@email.com",
    country: "Хорватия",
    citizenship: "Италия",
    direction: "Хорватия",
    status: "Завершён",
    manager: "Инспектор Marko Horvat",
    lastActivity: "10.05.2026",
    createdAt: "15.01.2026",
    passportNumber: "IT5566778",
    submittedAt: "15.01.2026",
    expectedApprovalAt: "20.04.2026",
    referentName: "Инспектор Marko Horvat",
    bookingAddress: "Zagreb, Ilica 42",
    bookingRange: "01.03.2026 — 05.03.2026",
    approvalAt: "12.04.2026",
    notes: "Одобрено ВНЖ",
    residenceCardIssuedAt: "25.04.2026",
  },
  {
    id: "CL-2002",
    name: "Avtandil K.",
    phone: "+995 555 123 456",
    email: "avtandil.k@email.com",
    country: "Хорватия",
    citizenship: "Грузия",
    direction: "Хорватия",
    status: "Завершён",
    manager: "Инспектор Ana Marić",
    lastActivity: "18.05.2026",
    createdAt: "10.02.2026",
    passportNumber: "GE3344556",
    submittedAt: "10.02.2026",
    expectedApprovalAt: "15.05.2026",
    referentName: "Инспектор Ana Marić",
    bookingAddress: "Rijeka, Korzo 8",
    bookingRange: "20.03.2026 — 22.03.2026",
    approvalAt: "08.05.2026",
    notes: "Одобрено",
    residenceCardIssuedAt: "20.05.2026",
  },
  {
    id: "CL-2003",
    name: "Leysan M.",
    phone: "+994 50 777 8899",
    email: "leysan.m@email.com",
    country: "Хорватия",
    citizenship: "Азербайджан",
    direction: "Хорватия",
    status: "В работе",
    manager: "Инспектор Ivan Perić",
    lastActivity: "28.05.2026",
    createdAt: "01.03.2026",
    passportNumber: "AZ7788990",
    submittedAt: "01.03.2026",
    expectedApprovalAt: "01.07.2026",
    referentName: "Инспектор Ivan Perić",
    bookingAddress: "Zadar, Široka ulica 3",
    bookingRange: "10.05.2026 — 12.05.2026",
    approvalAt: "—",
    notes: "Букинг пройден, ожидание решения MUP",
    residenceCardIssuedAt: "—",
  },
  {
    id: "CL-2004",
    name: "Petra Horvat",
    phone: "+385 98 111 2233",
    email: "petra.h@email.com",
    country: "Хорватия",
    citizenship: "Словения",
    direction: "Хорватия",
    status: "Завершён",
    manager: "Инспектор Ivan Perić",
    lastActivity: "15.04.2026",
    createdAt: "05.12.2025",
    passportNumber: "SI1122334",
    submittedAt: "05.12.2025",
    expectedApprovalAt: "01.03.2026",
    referentName: "Инспектор Ivan Perić",
    bookingAddress: "Zadar, Široka ulica 3",
    bookingRange: "20.01.2026 — 22.01.2026",
    approvalAt: "28.02.2026",
    notes: "Одобрено ВНЖ",
    residenceCardIssuedAt: "10.03.2026",
  },
];

const DEMO_SURVEYS: ClientSurvey[] = [
  {
    id: "SV-1",
    clientId: "CL-1001",
    title: "Анкета релокации",
    filledAt: "15.03.2026",
    processingStatus: "Обработана",
  },
  {
    id: "SV-2",
    clientId: "CL-1001",
    title: "Финансовый профиль",
    filledAt: "20.03.2026",
    processingStatus: "В обработке",
  },
  {
    id: "SV-3",
    clientId: "CL-1002",
    title: "Анкета Digital Nomad HR",
    filledAt: "10.04.2026",
    processingStatus: "Обработана",
  },
];

const DEMO_DOCUMENTS: ClientDocument[] = [
  {
    id: "DOC-1",
    clientId: "CL-1001",
    name: "passport_scan.pdf",
    uploadedAt: "14.03.2026",
    category: "паспорт",
  },
  {
    id: "DOC-2",
    clientId: "CL-1001",
    name: "income_statement.pdf",
    uploadedAt: "18.03.2026",
    category: "справка о доходах",
  },
  {
    id: "DOC-3",
    clientId: "CL-1002",
    name: "insurance.pdf",
    uploadedAt: "12.04.2026",
    category: "страховка",
  },
];

const demoNotesExtra: ClientNote[] = [];

export function getDemoNotes(clientId: string): ClientNote[] {
  const base = DEMO_NOTES.filter((n) => n.clientId === clientId);
  const extra = demoNotesExtra.filter((n) => n.clientId === clientId);
  return [...extra, ...base].sort((a, b) =>
    b.createdAt.localeCompare(a.createdAt),
  );
}

export function appendDemoNote(
  clientId: string,
  author: string,
  text: string,
): ClientNote {
  const note: ClientNote = {
    id: `NT-${Date.now()}`,
    clientId,
    createdAt: new Date().toLocaleDateString("ru-RU"),
    author,
    text,
  };
  demoNotesExtra.unshift(note);
  return note;
}

const DEMO_NOTES: ClientNote[] = [
  {
    id: "NT-1",
    clientId: "CL-1001",
    createdAt: "27.05.2026",
    author: "Менеджер 1",
    text: "Созвон состоялся. Клиент рассматривает Хорватию как запасной вариант.",
  },
  {
    id: "NT-2",
    clientId: "CL-1002",
    createdAt: "26.05.2026",
    author: "Менеджер 2",
    text: "Отправлен чек-лист документов для Digital Nomad визы.",
  },
];

export function getDemoClientDetail(id: string): ClientDetail | null {
  const client = DEMO_CLIENTS.find((c) => c.id === id);
  if (!client) return null;

  return {
    client,
    surveys: DEMO_SURVEYS.filter((s) => s.clientId === id),
    documents: DEMO_DOCUMENTS.filter((d) => d.clientId === id),
    notes: getDemoNotes(id),
    source: "demo",
  };
}
